@startuml

skinparam dpi 300

actor User as user
participant "API Server" as api
participant Operator as operator
participant "Alignment pod" as alignmentPod
participant "Prediction pod" as predictionPod
participant "Post processing pod" as postProcessingPod
database "Protein Database Volume" as dbVolume
database "Ephemeral Volume" as tmpVolume
database "AWS S3" as s3
queue "AWS SNS" as sns

user -> api : Creates\n//Protein//\n//Conformation//\n//Prediction//\nresource
api -> operator : Resource is\nbeing\nfetched
operator -> tmpVolume : Set up volume
group "Alignment Phase"
operator -> alignmentPod : Schedule job
alignmentPod -> dbVolume : Scan protein databases
alignmentPod -> alignmentPod : Perform\nMSA search\nand alignment
alignmentPod -> tmpVolume : Write alignment\ntemporal state
operator -> alignmentPod : Detect\njob finish
operator -> api : Update\nphase\nstatus
end
group "Prediction Phase"
operator -> predictionPod : Schedule prediction job
predictionPod -> tmpVolume : Load alignment\nartifacts
predictionPod -> predictionPod : Compute\nprotein structure
predictionPod -> tmpVolume : Write Machine Learning processing output
operator -> predictionPod : Detect\njob finish
operator -> api : Update\nphase\nstatus
end
group "Post Processing Phase"
operator -> postProcessingPod : Schedule post processing job
postProcessingPod -> tmpVolume : Read prediction artifacts
postProcessingPod -> s3 : Upload prediction artifacts
postProcessingPod -> sns : Send notifications
operator -> postProcessingPod : Detect\njob finish
operator -> api : Update\nphase\nstatus
end
user -> api : Monitor task status

@enduml