name: Build LaTeX document
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        continue-on-error: true
        uses: xu-cheng/latex-action@v3
        with:
          root_file: thesis.tex
          args: -file-line-error -interaction=nonstopmode -synctex=1 -output-format=pdf
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: thesis.pdf